FROM node:14-buster-slim
RUN mkdir /app

WORKDIR /app
COPY . .

RUN npm i
# RUN yarn build
# RUN cd build
# RUN yarn install --production
# RUN yarn apidoc
RUN node ace migration:run --force
# RUN yarn db:seed

EXPOSE 3333
CMD yarn dev 